# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f60adc04b92678d116cd08e121a8e0bc6d3fdb8a91e750bc32a2bca102def482ef734da02fdb59c947b90476153863c1cfa1f38cd4aa58e986057b735f74eee4

test:
  secret_key_base: 1c4f6daeade63866e43ec91cdb578531751a6dff43f971a701b2e8e60d62ed07c04f6ccea880e21af7e3d8643462d489efcd6553c9a68eec5f6f10e2c6f50256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# I dont want to show my secrets
/config/secrets.yml
